# This file was *autogenerated* from the file /home/totktonada/Programms/Git/sage-demo/HomeWork/graphs.sage
from sage.all_cmdline import *   # import sage library
_sage_const_2p0 = RealNumber('2.0')
def getCircleCoordinates(i, n):
    'Get coordinates for i-th vertex in a n-vertexed graph'
    x = cos(i  * _sage_const_2p0  * pi/ n)
    y = sin(i  * _sage_const_2p0  * pi/ n)
    return (x,y)

def getCoordsForVertices(graph):
    return {graph.vertices()[i]: getCircleCoordinates(i,len(graph.vertices())) for i in xrange(len(graph.vertices()))}


