# This file was *autogenerated* from the file makeStructure.sage
from sage.all_cmdline import *   # import sage library
_sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_2p0 = RealNumber('2.0'); _sage_const_0 = Integer(0); _sage_const_50 = Integer(50)
def getCircleCoordinates(i, n):
    'Get coordinates for i-th vertex in a n-vertexed graph'
    x = cos(i  * _sage_const_2p0  * pi/ n)
    y = sin(i  * _sage_const_2p0  * pi/ n)
    return (x,y)

def getCoordsForVertices(graph):
    return {graph.vertices()[i]: getCircleCoordinates(i,len(graph.vertices())) for i in xrange(len(graph.vertices()))}


def graphPlot(graph, marks = [], path = []):
    pic = Graphics()
    dic = getCoordsForVertices(graph)
    for i in graph.vertices():
        if i == path[_sage_const_0 ]:
            color = 'red'
            thicness = _sage_const_50 
        elif i == path[_sage_const_1 ]:
            color = 'blue'
            thicness = _sage_const_50 
        else:
            color = 'black'
            thicness = _sage_const_3 
        p = point(dic[i],color = color, size = thicness)
        pic += plot(p)
    for i in graph.edges():
        if i in marks:
            color = 'blue'
            thicness = _sage_const_3 
        else:
            color = 'black'
            thicness = _sage_const_1 
        pic += plot(line([dic[i[_sage_const_0 ]],dic[i[_sage_const_1 ]]], color = color, thickness = thicness))
    pic.axes(False)
    return pic

def showGraph(graph, marks = [], path = []):
    show(graphPlot(graph, marks, path ))

def itteration(graph, paths, start,end):
    marks = []
    for path in paths:
        for vert in graph.neighbors(path[-_sage_const_1 ]):
            if vert not in path:
                marks += [path+[vert]]
    return marks

def pathToEdge(paths):
    edges = []
    for j in paths:
        for i in xrange(_sage_const_1 ,len(j)):
            edges += [(j[i-_sage_const_1 ],j[i],None)]
    return edges

def listOfSteps(graph, start,end):
    paths = [[start]]
    marks = []
    pics = [graphPlot(graph,marks,[start,end])]
    while end not in map(lambda x: x[-_sage_const_1 ],paths) and len(paths)>_sage_const_0 :
        paths = itteration(graph,paths,start,end)
        marks = pathToEdge(paths)
        pics += [graphPlot(graph,marks,[start,end])]
    paths = filter(lambda x: x[-_sage_const_1 ] == end,paths)
    marks = pathToEdge(paths)
    pics += [graphPlot(graph,marks,[start,end])]
    return pics


r = graphs.RandomGNP(_sage_const_3 ,_sage_const_1 )
#r = graphs.RandomTree(15)
for i in listOfSteps(r,_sage_const_0 ,_sage_const_1 ):
    show(i)






